image: node:10.19.0

cache:
  paths:
    - node_modules/
    - .yarn

before_script:
  - yarn config set cache-folder .yarn
  - yarn install

stages:
  - build

build site:
  stage: build
  only:
    - v2
  script:
    - yarn build
