image: ruby:2.3

stages:
    - build

variables:
    JEKYLL_ENV: production
    LC_ALL: C.UTF-8

cache:
    paths:
        - vendor
    key: "$CI_BUILD_REPO"

before_script:
    - gem install bundler

build site:
    stage: deploy
    only:
        - master
    script:
        - bundle install --path=vendor/
        - bundle exec jekyll build
    artifacts:
        paths:
            - _site/
