language: ruby

cache: bundler

script:
    - JEKYLL_ENV=production bundle exec jekyll build --destination site

deploy:
    provider: pages
    local-dir: ./site
    target-branch: master
    email: hatamiarash7@gmail.com
    name: Deployment Bot
    skip-cleanup: true
    keep-history: true
