sudo: false

dist: trusty

language: ruby

cache: bundler

rvm:
  - 2.5.3

bundler_args: --without development

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

addons:
  apt:
    packages:
      - libcurl4-openssl-dev

jobs:
  include:
    - stage: Test
      script:
        - JEKYLL_ENV=production
        - bundle exec jekyll build
