# Site
title:              Arash Hatami
bio:                "Full Stack Developer @ Ateriad CGRC"
description:        "Full Stack Developer @ Ateriad CGRC"
reading_time:       true
words_per_minute:   200
logo:               "assets/img/logo.png"
background:         "assets/img/placeholder-big.jpg"
tiled_bg:           false
locale:             en_US
url:                https://arash-hatami.ir

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
    auto_ids:         true
    footnote_nr:      1
    entity_output:    as_char
    toc_levels:       1..6
    enable_coderay:   false
sass:
    sass_dir:         _sass
    style:            compressed

email:          hatamiarash7@gmail.com
github-url:     hatamiarash7
stackoverflow:  4905220/arash-hatami
linkedin:       hatamiarash7
instagram:      hatamiarash7

# Gems
plugins:
    - jekyll-mentions
    - jekyll-feed
    - jekyll-sitemap
    - jekyll-gist
    - jekyll_pdate_plugin
    - jekyll-include-cache
    - jekyll-analytics

jekyll-mentions:
    base_url: https://github.com

jekyll_analytics:
    GoogleAnalytics:
        id: UA-65859337-10
        anonymizeIp: false

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]

pdate_filter: "%A %d %B %Y"

staticman:
    repository: "hatamiarash7/MyWebSite"
    branch: master
    endpoint: # URL of your own deployment, with a trailing slash (will fallback to a public GitLab instance) eg. https://<your-api>/v3/entry/github/
    reCaptcha:
        # reCaptcha for Staticman (OPTIONAL, but recommended for spam protection)
        # If you use reCaptcha, you must also set these parameters in staticman.yml
        siteKey: # Use your own site key, you need to apply for one on Google
        secret: # ENCRYPT your password by going to https://staticman3.herokuapp.com/v3/encrypt/<your-site-secret>
