# Site
title:              Arash Hatami
bio:                "Full Stack Developer @ Ateriad CGRC"
description:        "Full Stack Developer @ Ateriad CGRC"
reading_time:       true
words_per_minute:   200
logo:               "assets/img/logo.png"
background:         "assets/img/placeholder-big.jpg"
tiled_bg:           false
locale:             en_US
url:                https://arash-hatami.ir

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
    auto_ids:         true
    footnote_nr:      1
    entity_output:    as_char
    toc_levels:       1..6
    enable_coderay:   false
sass:
    sass_dir:         _sass
    style:            compressed

email:  hatamiarash7@gmail.com
github-url:         hatamiarash7
stackoverflow:     4905220/arash-hatami
linkedin:          hatamiarash7
instagram:          hatamiarash7

# Gems
plugins:
    - jekyll-mentions
    - jekyll-feed
    - jekyll-sitemap
    - jekyll-gist
    - jekyll_pdate_plugin
    - jekyll-include-cache

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]

pdate_filter: "%A %d %B %Y"

theme: jekyll-theme-cayman