# Site
title:              Arash Hatami - Dev
bio:                "DevOps / NOC Engineer"
description:        "DevOps / NOC Engineer"
reading_time:       true
words_per_minute:   200
logo:               "assets/img/logo.webp"
background:         "assets/img/placeholder-big.webp"
tiled_bg:           false
locale:             en_US
url:                http://localhost:4000

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
    auto_ids:         true
    footnote_nr:      1
    entity_output:    as_char
    toc_levels:       1..6
    enable_coderay:   false
sass:
    sass_dir:         _sass
    style:            compressed

email:          hatamiarash7@gmail.com
github-url:     hatamiarash7
stackoverflow:  4905220/arash-hatami
linkedin:       hatamiarash7
instagram:      hatamiarash7

# Gems
plugins:
    - jekyll-mentions
    - jekyll-feed
    - jekyll-sitemap
    - jekyll-gist
    - jekyll_pdate_plugin
    - jekyll-include-cache
    - jekyll-analytics

jekyll-mentions:
    base_url: https://github.com

jekyll_analytics:
    GoogleAnalytics:
        id: UA-65859337-10
        anonymizeIp: false

# Exclude list
exclude: [.sass-cache, .idea, .github, README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, docker, CNAME, LICENSE, Rakefile, Dockerfile]

pdate_filter: "%A %d %B %Y"
