version: "3.7"

services:
  site:
    image: jekyll/jekyll:4.0.0
    container_name: arash_site
    restart: unless-stopped
    command: jekyll serve --config _dev_config.yml --watch --force_polling --verbose --trace -H 0.0.0.0
    volumes:
      - .:/srv/jekyll:rw
      - /docker/bundle:/usr/local/bundle
    environment:
      - JEKYLL_ENV=production
    ports:
        - 4000:4000
