version: "3.7"

services:
    jekyll:
        build:
            context: .
            dockerfile: Dockerfile
        image: hatamiarash7/site
        container_name: arash_website
        restart: always
        working_dir: /srv/jekyll
        environment:
            - JEKYLL_ENV=production
        ports:
            - 13003:4000
        volumes:
            - ./:/srv/jekyll
            - ./docker/bundle:/bundle
