version: '3.1'

services:
  ghost:
    build: .
    image: hatamiarash7/website-v3
    container_name: ghost
    restart: always
    environment:
      NODE_ENV: production
      url: "https://arash-hatami.ir"
      server__host: "0.0.0.0"
      server__port: 2369
      database__client: "sqlite3"
      database__connection__filename: "content/data/arash.db"
      database__useNullAsDefault: "true"
      database__debug: "false"
      paths__contentPath: "content/"
      logging__level: "info"
      logging__rotation__enabled: "true"
      logging__rotation__count: 15
      logging__rotation__period: "1d"
    volumes:
      - ./content:/home/arash/.build/release/content
    networks:
      - website
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.services.ghost.loadbalancer.server.port=2369"
      # HTTP
      - "traefik.http.routers.ghost.rule=Host(`arash-hatami.ir`)"
      - "traefik.http.routers.ghost.entrypoints=web"
      - "traefik.http.routers.ghost.service=ghost"
      # HTTPS
      - "traefik.http.routers.ghost-https.rule=Host(`arash-hatami.ir`)"
      - "traefik.http.routers.ghost-https.entrypoints=websecure"
      - "traefik.http.routers.ghost-https.service=ghost"

networks:
  website:
    external: false
    driver: bridge
  traefik:
    external: true
