version: "3"

services:
  app:
    container_name: website-docusaurus
    image: website-docusaurus
    restart: unless-stopped
    working_dir: /code
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    expose:
      - 3000

  nginx:
    container_name: website-nginx
    image: website-nginx
    build: ./docker/nginx
    restart: unless-stopped
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
    ports:
      - 13003:80
    depends_on:
      - app
