version: "3"

services:
  app:
    container_name: website-docusaurus
    image: website-docusaurus
    restart: unless-stopped
    working_dir: /code
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    ports:
      - 13003:3000
