backend:
    name: github
    repo: hatamiarash7/MyWebSite
    branch: master
    site_domain: arash-hatami.ir
    accept-roles:
        - admin

media_folder: "assets/img/posts"

collections:
    - name: "post"
      label: "Post"
      folder: "_posts"
      create: true
      slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
      fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
